[profile.default]
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "contracts/out"
solc_version = "0.8.26"
src = "contracts/src"
test = "contracts/test"
via_ir = false
optimizer = true
optimizer_runs = 200

[profile.default.optimizer_details]
peephole = true
inliner = true
jumpdestRemover = true
orderLiterals = true
deduplicate = true
cse = true
constantOptimizer = true
yul = true

[profile.default.yul_details]
stackAllocation = true
optimizerSteps = "dhfoDgvulfnTUtnIf"

[rpc_endpoints]
anvil = "http://localhost:8545"
holesky = "https://holesky.rpc.thirdweb.com"
mainnet = "https://eth-mainnet.g.alchemy.com/v2/LF_kKjuhP-n6j9O-jWcg9o94UWKNtoCf"
mainnet_fork = "https://eth-mainnet.g.alchemy.com/v2/LF_kKjuhP-n6j9O-jWcg9o94UWKNtoCf"

[etherscan]
holesky = { key = "${HOlesky_ETHERSCAN_API_KEY}" }

